experiment_name: "test"
logging_root: "./logs"
model_type: "sine"
plot: True

image:
  num_epochs: 4 # 100000
  epochs_til_print: 1 # 10000
  resolution: 256
  batch_size: 1
  lr: 1e-4
audio:
  num_epochs: 4
  epochs_til_print: 1
  batch_size: 1
  lr: 1e-4
video:
  dataset: "bunny"
  num_epochs: 4
  epochs_til_print: 1
  sample_frac: 38e-2
  batch_size: 1
  lr: 1e-4
sdf:
  num_epochs: 15000
  epochs_til_print: 1000
  batch_size: 5000
  lr: 1e-4